name: Release Publish

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
      - run: ./gradlew distZip
#      - run: ./gradlew nativeCompile
#      - run: ls -lR ${project.name}-${project.version}/
#      - name: Verify file exists
#        run: ls -l ./build/*.zip
      - run: ls -l ./build/distributions/allure-testops-utils-1.0-SNAPSHOT.zip
      - run: ls -l ./build/distributions/${project.name}-${project.version}*.zip
      - run: ls -l ./build/distributions/${project.name}-${project.version}.zip
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./build/distributions/${project.name}-${project.version}*.zip
          asset_name: "${{ github.event.repository.name }}-${{ github.ref_name }}.zip"
          asset_content_type: application/zip
