name: Release Publish

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
      - run: ./gradlew build
      - run: ./gradlew nativeCompile
      - run: ls -lR ./build
      - run: ./gradlew bundleDistribution --info
      - run: ls -lR ${project.name}-${project.version}/
      - name: Verify file exists
        run: ls -l ./build/*.zip
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/*.zip
          asset_name: "${{ github.event.repository.name }}-${{ github.ref_name }}.zip"
          asset_content_type: application/zip
