name: Release Publish

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
      - run: ./gradlew build
      - run: ls -la ./build/distributions
        name: list possible distributions if next step fails, check it and update file path
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/distributions/allure-testops-utils-1.0-SNAPSHOT.zip
          asset_name: "${{ github.event.repository.name }}-${{ github.ref_name }}.zip"
          asset_content_type: application/zip
